// Task 1.12 (arch §13.2). Job-type constants live in code, not a DB enum —
// `OutboxJob.type` is a plain String column, kept extensible per Task 1.1's
// schema comment.
export const JOB_TYPES = {
  EMAIL_TRAINER_INVITE: 'EMAIL_TRAINER_INVITE',
  EMAIL_COACH_INVITE: 'EMAIL_COACH_INVITE',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  EMAIL_PASSWORD_RESET: 'EMAIL_PASSWORD_RESET',
  EMAIL_SHARELINK_CONFIRMATION: 'EMAIL_SHARELINK_CONFIRMATION',
  EMAIL_CHILD_BLOCKED_SHARELINK: 'EMAIL_CHILD_BLOCKED_SHARELINK',
  EMAIL_CHILD_APPROVAL_REQUEST: 'EMAIL_CHILD_APPROVAL_REQUEST',
  EMAIL_CHILD_APPROVAL_DECISION: 'EMAIL_CHILD_APPROVAL_DECISION',
  EMAIL_COACH_OVERRIDE_NOTIFY: 'EMAIL_COACH_OVERRIDE_NOTIFY',
  MEDIA_THUMBNAIL: 'MEDIA_THUMBNAIL',
  MEDIA_LOGO_RESIZE: 'MEDIA_LOGO_RESIZE',
} as const;

export type JobType = (typeof JOB_TYPES)[keyof typeof JOB_TYPES];

export const EMAIL_JOB_TYPES: ReadonlySet<JobType> = new Set([
  JOB_TYPES.EMAIL_TRAINER_INVITE,
  JOB_TYPES.EMAIL_COACH_INVITE,
  JOB_TYPES.EMAIL_VERIFICATION,
  JOB_TYPES.EMAIL_PASSWORD_RESET,
  JOB_TYPES.EMAIL_SHARELINK_CONFIRMATION,
  JOB_TYPES.EMAIL_CHILD_BLOCKED_SHARELINK,
  JOB_TYPES.EMAIL_CHILD_APPROVAL_REQUEST,
  JOB_TYPES.EMAIL_CHILD_APPROVAL_DECISION,
  JOB_TYPES.EMAIL_COACH_OVERRIDE_NOTIFY,
]);

export const MEDIA_JOB_TYPES: ReadonlySet<JobType> = new Set([JOB_TYPES.MEDIA_THUMBNAIL, JOB_TYPES.MEDIA_LOGO_RESIZE]);
